In [16]:
import numpy as np
import pandas as pd

from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [17]:

housing = fetch_california_housing()

df = pd.DataFrame(housing.data, columns=housing.feature_names)

df['price'] = housing.target

df.head()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,price
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422

In [18]:
df.isna().sum()

MedInc        0
HouseAge      0
AveRooms      0
AveBedrms     0
Population    0
AveOccup      0
Latitude      0
Longitude     0
price         0
dtype: int64

### There is no missing values in the dataset.

## feature scalling

In [19]:
#split feature
x = df.drop('price',axis=1)
y = df['price']

x_train,x_test, y_train,y_test = train_test_split(x,y,test_size=0.2, random_state = 42)

#scaling
scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

feature scaling is applied to normalize the data.

## Regression Algorithm Implementation

In [20]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor,GradientBoostingRegressor
from sklearn.svm import SVR

In [21]:
models = {
    "Linear Regression" : LinearRegression(),
    "Decision Tree": DecisionTreeRegressor(),
    "Random Forest" : RandomForestRegressor(),
    "Gradient Boosting" : GradientBoostingRegressor(),
    "SVR" : SVR()
}

In [22]:
trained_models = {}

for name, model in models.items():
    if name == "SVR":
        model.fit(x_train_scaled, y_train)
        trained_models[name] = model
    else:
        model.fit(x_train, y_train)
        trained_models[name] = model

### Algorithm Explanation
1. Linear Regression:
   A simple algorithm that models the relationship between dependent and independent variables using a straight line.

2. Decision Tree:
   Splits the data into smaller subsets based on feature values.

3. Random Forest:
   An ensemble method that combines multiple decision trees to improve accuracy.

4. Gradient Boosting:
   Builds models sequentially to correct errors made by previous models.

5. Support Vector Regressor (SVR):
   Uses hyperplanes to predict continuous values and works well with scaled data.

## Model Evaluation and Comparison

In [23]:
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

In [25]:
results = []

for name, model in trained_models.items():
    
    if name == "SVR":
        y_pred = model.predict(x_test_scaled)
    else:
        y_pred = model.predict(x_test)
    
    mse = mean_squared_error(y_test, y_pred)
    mae = mean_absolute_error(y_test, y_pred)
    r2 = r2_score(y_test, y_pred)
    
    results.append([name, mse, mae, r2])

# Convert to DataFrame
results_df = pd.DataFrame(results, columns=["Model", "MSE", "MAE", "R2 Score"])
results_df

               Model       MSE       MAE  R2 Score
0  Linear Regression  0.555892  0.533200  0.575788
1      Decision Tree  0.499046  0.455023  0.619168
2      Random Forest  0.252839  0.325680  0.807053
3  Gradient Boosting  0.294079  0.371716  0.775582
4                SVR  0.357004  0.398599  0.727563

In [26]:
best_model = results_df.loc[results_df['R2 Score'].idxmax()]
worst_model = results_df.loc[results_df['R2 Score'].idxmin()]

print("Best Model:\n", best_model)
print("\nWorst Model:\n", worst_model)

Best Model:
 Model       Random Forest
MSE              0.252839
MAE               0.32568
R2 Score         0.807053
Name: 2, dtype: object

Worst Model:
 Model       Linear Regression
MSE                  0.555892
MAE                    0.5332
R2 Score             0.575788
Name: 0, dtype: object

The best model is the one with the highest R² score because it explains the variance better.

Tree-based models like Random Forest and Gradient Boosting usually perform better for this dataset.

The worst model has the lowest R² score and higher error values.

Linear Regression is not suitable for this model.